### ISSUE TITLE
add bullmq support

### ISSUE THREAD

**Issue by skeggse** [bee-queue/docker-arena#37]
Just need to add bullmq as a project dependency and provide it [in the index script](https://github.com/bee-queue/docker-arena/blob/a7547bd85e8683c3b81de3836173255076b5be09/index.js#L14-L22). Per bee-queue/arena#248.

**Comment by gtpan77** [comment]
Hey @skeggse, I'd like to work on this issue. I understand we have to add bullmq as package dependency. But I didn't understand what is index script and where is index.json.

**Comment by skeggse** [comment]
Hey, awesome!

>what is index script

[`index.js`](https://github.com/bee-queue/docker-arena/blob/default/index.js) - we just gotta lazily import it there

>where is index.json

it's optional and gets mounted via docker per the README:

```sh
$ docker run -p 4567:4567 -v </local/route/to/index.json>:/opt/arena/index.json <name-image>
```

so theoretically it's just handled by `arena` upstream
